### ISSUE TITLE
python exception

### ISSUE THREAD

**Issue by barosch78** [deimosfr/galera_innoptimizer#1]
i get an exception while running the tool.
it seems like a general problem and not related to a special database.

i created a simple database with:
create database test;
create table test (id int, value varchar(100));

explain partitions select \* from test.test;
+------+-------------+-------+------------+------+---------------+------+---------+------+------+-------+
| id   | select_type | table | partitions | type | possible_keys | key  | key_len | ref  | rows | Extra |
+------+-------------+-------+------------+------+---------------+------+---------+------+------+-------+
|    1 | SIMPLE      | test  | NULL       | ALL  | NULL          | NULL | NULL    | NULL |    1 |       |
+------+-------------+-------+------------+------+---------------+------+---------+------+------+-------+

the error is:
./ginnoptimizer.py -d test -u root -p XXXXX
[+] Trying to connect to MySQL/MariaDB instance...OK
[+] Checking current Galera state... 
  -> wsrep_ready status...OK
  -> wsrep_cluster status...OK
  -> wsrep_connected status...OK
  -> wsrep_desync status...OK
  -> wsrep_OSU_method status...OK
[+] Getting list of all tables in test database...OK
[+] Enabling RSU mode...OK
[+] Starting optimization on test database... 
  -> wsrep_flow_control_paused status > 0.3...OK
Traceback (most recent call last):
  File "./ginnoptimizer.py", line 462, in <module>
    main()
  File "./ginnoptimizer.py", line 459, in main
    args()
  File "./ginnoptimizer.py", line 450, in args
    optimize_rsu(database, tables_list, fcpmax)
  File "./ginnoptimizer.py", line 203, in optimize_rsu
    launch_sql_queries(table)
  File "./ginnoptimizer.py", line 174, in launch_sql_queries
    partitions = ptables[0][3].split(',')
AttributeError: 'NoneType' object has no attribute 'split'

Python version:
Python 2.7.3
Galera version:
5.5.40-MariaDB-1~wheezy-wsrep-log mariadb.org binary distribution, wsrep_25.11.r4026

**Comment by kreynolds** [comment]
The problem appears to be when partitions is NULL instead of something. 

``` python
if ptables[0][3] == None:
  partitions = ['no partitions']
else:
  partitions = ptables[0][3].split(',')
```

There is probably a more graceful way of handling this in concise python syntax but I'm not an expert at that. There are a number of other errors but I'll file them in other issues.
