### ISSUE TITLE
Puppet module

### ISSUE THREAD

**Issue by djjudas21** [deimosfr/galera_innoptimizer#11]
Hi there,

Not really an issue so feel free to close this right away... Just wanted to let you know I've written a Puppet module to deploy this script. Might be helpful to someone else who is using Galera and Puppet.
- https://github.com/djjudas21/puppet-galera-innoptimizer
- https://forge.puppet.com/jgazeley/galera_innoptimizer

Cheers,
Jonathan

**Comment by deimosfr** [comment]
Thanks !
