### ISSUE TITLE
Script crash leaving node desynced after upgrade.

### ISSUE THREAD

**Issue by iamacarpet** [deimosfr/galera_innoptimizer#7]
Hello,

After upgrading our cluster to percona-xtradb-cluster-server version 5.6.28-25.14-1, our next scheduled runs of this script left the nodes desynced.

I ran it manually and discovered it was crashing when trying to resync after the first DB.
Got the following stack trace:

```
[+] Restoring TOI mode...
  -> wsrep_on status.............................................
Traceback (most recent call last):
  File "galera_opt.py", line 512, in <module>
    main()
  File "galera_opt.py", line 509, in main
    args()
  File "galera_opt.py", line 500, in args
    optimize_rsu(database, tables_list, fcpmax)
  File "galera_opt.py", line 253, in optimize_rsu
    restore_toi()
  File "galera_opt.py", line 165, in restore_toi
    'wsrep_on', 'ON', 'SET GLOBAL wsrep_on=ON;')
  File "galera_opt.py", line 315, in check_and_set_param
    if (wsrep_param[0][1] != value):
IndexError: list index out of range
```

Tried running `SET GLOBAL wsrep_on=ON;` manually and got:
`ERROR 1228 (HY000): Variable 'wsrep_on' is a SESSION variable and can't be used with SET GLOBAL`

Fixed for now by commenting out lines 164-165, but there is probably a better way.

Thanks,
iamacarpet

**Comment by enableit** [comment]
I think this is due to wsrep_on being a session variable. Earlier versions of MySQL/Galera returned a value when the global variable wsrep_on was queried, later ones did not. Removing the GLOBAL keyword from line 164 fixes the problem for us.

**Comment by deimosfr** [comment]
Can you please make a PR with what is working for you please?

**Comment by enableit** [comment]
Hi @deimosfr, it's just on line 171 https://github.com/deimosfr/galera_innoptimizer/blob/master/ginnoptimizer.py#L171 (sorry I thought it was 164 but I may have an older version)

wsrep_on is not a GLOBAL variable, it's a session variable (see http://galeracluster.com/documentation-webpages/mysqlwsrepoptions.html)

Either this changed in a new version of Galera, or the older version of MySQL also had the variable in the global scope, but for us running MySQL 5.6.34 we need to remove the "GLOBAL" from ginnooptimizer.py. When using MariaDB 5.5.5-10.0.28 the GLOBAL works ok.
